"use client";
import {useEffect,useRef,useState} from 'react';
import {flushSync} from 'react-dom';
import {Sparkles,Shuffle,Sun,BookOpen,Leaf,FlaskConical,Sigma,Atom,Brain,Globe2,LoaderCircle,SlidersHorizontal,X,Info,RotateCcw,Plus,Minus,Check} from 'lucide-react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Dialog,DialogTrigger,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Input} from '@/components/ui/input';
import {defaultFilters,subjects,discover,buildQuery,dayKey,hash,type Filters,type Paper} from '@/lib/science';
import seedData from '@/lib/data/seeds.json';
import {LibraryPanel} from '@/components/library-panel';
const seeds=seedData as Paper[];
const subjectsUI=[{name:'Everything',icon:Sparkles},{name:'Biology',icon:Leaf},{name:'Chemistry',icon:FlaskConical},{name:'Math',icon:Sigma},{name:'Physics',icon:Atom},{name:'Psychology',icon:Brain},{name:'Earth science',icon:Globe2}];
const artworks=[{file:'ecology-friends.png',alt:'A cheerful plant and planet Earth sharing a microscope'},{file:'curious-brain.png',alt:'A curious cartoon brain wearing star glasses and holding a magnifying glass'},{file:'cosmic-curiosity.png',alt:'A smiling pink planet beside a little robot astronaut'}];
const captions=['Small things. Big ideas.','A little food for thought.','Wonder looks good on you.','Follow the rabbit hole.'];
const initial:Paper={...(seeds.find(p=>p.pmcid==='PMC13553068')||seeds[0]),discipline:'Biology',headline:'A yak’s best friend might be a tiny gardener.',hook:'Pika are often treated as pests. But in this grassland study, having some around helped yaks gain more weight.',explanation:'Think of pika as tiny gardeners with a very particular weeding habit. They clip a poisonous plant, leaving more room for grasses that yaks can eat. In summer field experiments on the Qinghai–Tibetan Plateau, yaks gained up to 42% more weight where pika were present. The benefit was strongest at moderate pika numbers. Too many pika became competitors for the same food.',importance:'Removing every small herbivore could backfire. Managing the balance between species may sometimes help livestock more than eliminating an apparent pest.',caveat:'This was one grassland system studied in summer. It does not show the same benefit in every season, landscape, or herd.'};
export default function Home(){
 const [filters,setFilters]=useState<Filters>(defaultFilters),[paper,setPaper]=useState<Paper>(initial),[daily,setDaily]=useState(true),[advanced,setAdvanced]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState(''),[art,setArt]=useState(0),[caption,setCaption]=useState(0),[date,setDate]=useState(''),[reads,setReads]=useState(0),[sourceOpen,setSourceOpen]=useState(false);
 const seen=useRef(new Set<string>([initial.pmcid])),working=useRef(false),controller=useRef<AbortController|null>(null),dailyPaper=useRef(initial),editorial=useRef<Record<string,any>>({});
 useEffect(()=>{const day=dayKey();setDate(day);fetch('/editorial.json').then(async r=>r.ok?await r.json():{}).then((data:any)=>{editorial.current=data;const chosen=seeds[hash(day)%seeds.length];const pick={...chosen,...data[chosen.pmcid]};dailyPaper.current=pick;setPaper(p=>p.pmcid===initial.pmcid?pick:p);seen.current.add(pick.pmcid)}).catch(()=>{});return()=>controller.current?.abort()},[]);
 function change(values:Partial<Filters>){setFilters(f=>({...f,...values}));setError('')}
 function remix(){setArt(i=>(i+1+Math.floor(Math.random()*2))%artworks.length);setCaption(i=>(i+1)%captions.length)}
 async function shuffle(override?:Filters){if(working.current)throw new Error('Already finding a paper.');const selected=override||filters;try{buildQuery(selected)}catch(e){setError((e as Error).message);throw e}working.current=true;setBusy(true);setError('');setStatus('Looking for your next rabbit hole…');const ctl=new AbortController();controller.current=ctl;try{const result=await discover(selected,seen.current,ctl.signal,paper.pmcid);const next={...result.paper,...editorial.current[result.paper.pmcid]};seen.current.add(next.pmcid);flushSync(()=>{setPaper(next);setFilters(selected);setDaily(false);setReads(n=>n+1);setStatus('New paper, new perspective.');setSourceOpen(false);remix()});return {pmcid:next.pmcid,title:next.title,source:next.articleUrl}}catch(e){const message=e instanceof Error?e.message:'Please try again.';setError(/timeout/i.test(message)?'The journal library is taking a little too long. Try again in a moment.':message);setStatus('');throw e}finally{working.current=false;setBusy(false)}}
 function showDaily(){if(busy)return;setPaper(dailyPaper.current);setDaily(true);setError('');setStatus('Today’s pick is back.');setSourceOpen(false)}
 const actions=useRef({shuffle,filters});actions.current={shuffle,filters};
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const life=new AbortController();try{Promise.resolve(context.registerTool({name:'discover_scientific_paper',title:'Discover a scientific paper',description:'Shuffle an unread scientific article and display its publisher explanation on Paper Girl.',inputSchema:{type:'object',properties:{subject:{type:'string',enum:Object.keys(subjects)},period:{type:'string',enum:['any','recent','older','custom']},from:{type:'string'},to:{type:'string'}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},async execute(input:any){if(!input||typeof input!=='object'||Array.isArray(input)||Object.entries(input).some(([k,v])=>!['subject','period','from','to'].includes(k)||typeof v!=='string'))throw new Error('Invalid filters.');const f={...actions.current.filters,...(input.subject?{topic:input.subject}:{}),...(input.period?{period:input.period}:{}),...(input.from?{from:input.from}:{}),...(input.to?{to:input.to}:{})};buildQuery(f);return actions.current.shuffle(f)}},{signal:life.signal})).catch(()=>{})}catch{}return()=>life.abort()},[]);
 const edited=!!paper.hook;const p=paper.summaryParagraphs;
 const hook=paper.hook||p[0]||'';const explanation=paper.explanation||p.slice(1,-1).join('\n\n');const importance=paper.importance||p[p.length-1]||'';
 const topic=paper.discipline||paper.topic||'Science';const wordCount=(edited?[hook,explanation,importance]:p).join(' ').split(/\s+/).length;
 return <div className="site"><header><a className="brand" href="/">paper<span>girl</span><Sparkles size={23}/></a><span className="header-note">a little science. a lot of curiosity.</span><button onClick={showDaily} disabled={busy} className={daily?'daily-link active':'daily-link'}><Sun size={16}/> Today’s paper</button></header>
 <main><div className="above-card"><span><Sparkles size={14}/>{daily?'YOUR PAPER OF THE DAY':'YOUR NEW RABBIT HOLE'}</span><span>{date?new Date(date+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric'}):''}</span></div>
 <article className="paper-card" aria-busy={busy}><div className="paper-copy" key={paper.pmcid}><div className="paper-meta"><span className="subject-tag">{topic}</span><span>{paper.journal} <i>·</i> {paper.year}</span><span className="read-time">{Math.max(1,Math.ceil(wordCount/180))} min read</span></div><h1 className={((paper.headline||paper.title).length>95)?'long-title':''}>{paper.headline||paper.title.replace(/\.$/,'')}</h1>
 {edited?<><div className="story-section hook"><span className="section-label"><span>01</span> THE STRANGE HOOK</span><p>{hook}</p></div><div className="story-section"><span className="section-label"><span>02</span> THE COOL EXPLANATION</span>{explanation.split('\n\n').map((text,i)=><p key={i}>{text}</p>)}</div><div className="story-section significance"><span className="section-label"><span>03</span> WHY IT MATTERS</span><p>{importance}</p></div></>:<div className="story-section"><span className="section-label">THE PUBLISHER EXPLAINS</span>{p.map((text,i)=><p key={i}>{text}</p>)}</div>}
 {paper.caveat&&<div className="reality-check"><Info size={15}/><p><strong>The small print:</strong> {paper.caveat}</p></div>}
 <div className="attribution">{edited?'Plain-English take by Paper Girl, based on the publisher digest.':'Publisher-written explanation, reproduced in full.'} <button onClick={()=>setSourceOpen(!sourceOpen)} aria-expanded={sourceOpen} aria-controls="research-details">{sourceOpen?'Hide source details':'Source details'}</button></div>
 {sourceOpen&&<div id="research-details" className="research-details"><h2>{paper.title}</h2><p>{paper.authors}</p><p>Published {paper.publicationDate} · DOI {paper.doi||'not supplied'}</p><p>{paper.copyright||paper.authors} · <a href={paper.licenseUrl} target="_blank" rel="noreferrer">Creative Commons attribution license</a></p><p>{edited?'The metaphor and wording are ours; the findings and study limits come from the cited paper.':'Publisher paragraphs are displayed once, in their original order. Publisher explanations may contain technical terms.'}</p><details><summary>Full publisher explanation</summary>{p.map((t,i)=><p key={i}>{t}</p>)}</details><a href={paper.fullTextUrl} target="_blank" rel="noreferrer">Full text at Europe PMC</a></div>}
 <a className="original-link" href={paper.articleUrl} target="_blank" rel="noreferrer"><BookOpen size={16}/> Read the original paper <span>OPEN ACCESS</span></a></div>
 <aside className="art-panel"><div className="window-chrome"><span aria-hidden="true"><i/><i/><i/></span><span>curiosity.exe</span><Sparkles size={13}/></div><div className="art-image"><img src={'/art/'+artworks[art].file} width={1024} height={1024} alt={artworks[art].alt}/></div><div className="art-caption"><span>{captions[caption]}</span><button onClick={remix} aria-label="Remix cartoon" title="Remix cartoon"><Shuffle size={17}/></button></div><span className="art-note">a little illustration, just for fun</span><div className="margin-note"><Sparkles size={20}/><p>Stay curious,<br/><em>sweet thing.</em></p></div></aside></article>
 <section className="controls" aria-label="Pick your next paper"><div className="controls-heading"><h2>Your next rabbit hole</h2><button className="date-toggle" aria-expanded={advanced} aria-controls="year-controls" onClick={()=>setAdvanced(!advanced)}><SlidersHorizontal size={14}/>{filters.period==='any'?'Any year':filters.period==='recent'?'Past year':filters.period==='older'?'5+ years ago':`${filters.from}–${filters.to}`} {advanced?<Minus size={13}/>:<Plus size={13}/>}</button></div><div className="subject-row">{subjectsUI.map(({name,icon:Icon})=><button key={name} className={filters.topic===name?'subject active':'subject'} aria-pressed={filters.topic===name} onClick={()=>change({topic:name})} disabled={busy}><Icon size={15}/>{name}</button>)}</div>
 {advanced&&<div className="year-controls" id="year-controls"><label id="year-label">Published</label><Select value={filters.period} onValueChange={v=>change({period:v})} disabled={busy}><SelectTrigger aria-labelledby="year-label"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="any">Any year</SelectItem><SelectItem value="recent">Past 12 months</SelectItem><SelectItem value="older">At least 5 years ago</SelectItem><SelectItem value="custom">Choose years</SelectItem></SelectContent></Select>{filters.period==='custom'&&<div className="year-range"><Input type="number" aria-label="First year" min={1900} max={new Date().getFullYear()} value={filters.from} onChange={e=>change({from:e.target.value})} disabled={busy}/><span>to</span><Input type="number" aria-label="Last year" min={1900} max={new Date().getFullYear()} value={filters.to} onChange={e=>change({to:e.target.value})} disabled={busy}/></div>}<button className="reset" disabled={busy} onClick={()=>{setFilters(defaultFilters);setError('');setStatus('Filters reset. Your reading history is saved.')}}><RotateCcw size={13}/> Reset</button></div>}
 <div className="shuffle-row"><p>No paywalls here. Just one more “wait, really?”</p><button className="shuffle-button" disabled={busy} onClick={()=>{shuffle().catch(()=>{})}}>{busy?<LoaderCircle size={20} className="spin"/>:<Shuffle size={20}/>} {busy?'Finding a paper…':'Surprise me'} {!busy&&<Sparkles size={16}/>}</button></div><div role="status" aria-live="polite" className="status">{status}{reads>0&&!busy&&<span>{reads} new {reads===1?'discovery':'discoveries'} this session</span>}</div>{error&&<div className="error" role="alert"><Info size={17}/><p>{error}</p><button onClick={()=>setError('')} aria-label="Dismiss message"><X size={16}/></button></div>}</section>
 <LibraryPanel revision={reads}/><footer><span>Made for curious minds. Always free.</span><Dialog><DialogTrigger asChild><button>Where the science comes from</button></DialogTrigger><DialogContent className="source-dialog"><DialogTitle>The science behind Paper Girl</DialogTitle><DialogDescription>Clear explanations. Real sources. No subscriptions.</DialogDescription><div className="source-dialog-copy"><h3>Our journal shelf</h3><p>Live discovery searches <a href="https://europepmc.org/RestfulWebService" target="_blank" rel="noreferrer">Europe PMC</a> for open-access research in <a href="https://elifesciences.org/" target="_blank" rel="noreferrer">eLife</a>, PLOS Biology, PLOS Genetics, PLOS Computational Biology, PLOS Pathogens and PLOS Neglected Tropical Diseases. Original papers open on their journal websites.</p><h3>Simple subjects, honest coverage</h3><p>Biology and health are our strongest areas. Chemistry includes biochemistry; Math includes mathematical modeling; Physics includes biological physics. Earth science covers ecosystems, climate and fossils. Subject filters match titles and abstracts, so topics may overlap. This library does not cover every branch of science.</p><h3>Words and metaphors</h3><p>Daily picks rotate through a prepared collection with edited plain-English explanations. We use metaphors only where they fit the mechanism, keep the study’s actual scope, and include a specific limitation. Live papers use the publisher’s own complete digest or author summary. Some publisher text is more technical. We do not invent a metaphor or conclusion for it.</p><h3>What we check</h3><p>Live finds must have an accessible publisher summary and a CC BY license. We skip reviews, preprints and known retraction or concern notices present in the index. These checks are not a guarantee that a study’s conclusion is correct. One study is one piece of evidence.</p><h3>Keep exploring, for free</h3><p>The article index covers the supported open-access collection. Summaries are checked when selected. An anonymous browser cookie remembers articles you have read across visits; clearing cookies starts a new reading history. Every search is saved in the shared history with its filters, time and outcome. Names, emails and account IDs are not stored. Narrow filters can run out; widen them to keep exploring.</p><p>Daily picks were prepared October 4, 2026. The cartoon button remixes three original illustrations, not scientific diagrams. There is no paid AI service, subscription, or payment collection.</p></div></DialogContent></Dialog></footer>
 </main></div>
}
